/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sofware_EnvioMensajesAguaCarabayllo.view;
import Sofware_EnvioMensajesAguaCarabayllo.model.ConexionSQL;
import static com.mycompany.smsform.MensajesSMS.ACCOUNT_SID;
import static com.mycompany.smsform.MensajesSMS.AUTH_TOKEN;
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class EnvioMensaje extends javax.swing.JFrame {

    public static final String ACCOUNT_SID = "ACd5071b739a2f1a38dd50c1cc5965f02d";
    public static final String AUTH_TOKEN = "0340a003ba8d248008d7ab4889e2a783";
    private String numero = "+17162612330";
    public EnvioMensaje() {
        initComponents();
        // Agregar el ActionListener al botón
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Llamar al método que envía el mensaje y guarda en la base de datos
                enviarYGuardarMensaje();
            }
        });
    }
 private void enviarYGuardarMensaje() {
        // Obtener el contenido del campo txtMensaje
        String mensaje = txtMensaje.getText();

        // Supongamos que ya tienes una instancia de la clase conexionSQl que proporciona la conexión
        ConexionSQL conexionSQL = new ConexionSQL();
        Connection conexion = conexionSQL.getConnection();

        // Supongamos que ya tienes un número y un usuario (puedes obtenerlos de algún lugar)
        int numero = 1;
        String usuario = "Usuario1";

        // Crear la consulta SQL para insertar el mensaje en la tabla Mensajes
        String sql = "INSERT INTO Mensajes (Numero, Usuario, Mensaje) VALUES (?, ?, ?)";

        try (PreparedStatement statement = conexion.prepareStatement(sql)) {
            statement.setInt(1, numero);
            statement.setString(2, usuario);
            statement.setString(3, mensaje);

            // Ejecutar la consulta
            statement.executeUpdate();

            // Simular el envío del mensaje a través del servicio ficticio
        //    ServicioMensajes.enviarMensaje(numero, mensaje);

            System.out.println("Mensaje guardado y enviado exitosamente.");

        } catch (SQLException ex) {
            System.err.println("Error al guardar el mensaje: " + ex.getMessage());
        } finally {
            // Cerrar la conexión después de su uso
            conexionSQL.cerrarConexion();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContactos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnConductor = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabecera.setBackground(new java.awt.Color(201, 50, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Message");
        Cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel10.setText("Municipalida distrital de Carabayllo");
        Cabecera.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 410, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel11.setText("Envio               ");
        Cabecera.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jPanel1.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/284-F5-1300 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 140));

        jPanel2.setBackground(new java.awt.Color(188, 163, 175));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(201, 50, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jButton1.setText("Crear Mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        jButton2.setBackground(new java.awt.Color(201, 50, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo-de-contacto.png"))); // NOI18N
        jButton2.setText("Contactos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 79));

        jButton3.setBackground(new java.awt.Color(201, 50, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/todos.png"))); // NOI18N
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 240));

        jPanel3.setBackground(new java.awt.Color(150, 110, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HORARIOS DE  ENTREGA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel6.setBackground(new java.awt.Color(164, 74, 12));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("ELEGIR HORARIO");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 12, -1, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Dia");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Mes");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Año");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 180, 50));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 32));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 32));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, 32));

        jButton4.setBackground(new java.awt.Color(224, 57, 57));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexible.png"))); // NOI18N
        jButton4.setText("GUARDAR HORARIO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 460, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 910, 220));

        jPanel4.setBackground(new java.awt.Color(150, 110, 110));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Numero"
            }
        ));
        jScrollPane1.setViewportView(tbContactos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Contactos:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Redactar mensaje:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 30));
        jPanel4.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 570, 130));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 910, 260));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, 140, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Mensaje:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total de caracteres:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 650, -1, -1));

        btnConductor.setBackground(new java.awt.Color(201, 50, 0));
        btnConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chofer.png"))); // NOI18N
        btnConductor.setText("Conductor");
        btnConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductorActionPerformed(evt);
            }
        });
        jPanel1.add(btnConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 140, 50));

        jButton6.setBackground(new java.awt.Color(201, 50, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 140, 50));

        jButton7.setBackground(new java.awt.Color(201, 50, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviar-mensaje.png"))); // NOI18N
        jButton7.setText("Enviar Mensaje");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 600, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Establecer la conexión a la base de datos
    ConexionSQL conexionSQL = new ConexionSQL();

    try (Connection connection = conexionSQL.getConnection()) {
        // Consulta SQL para obtener ID, Usuario y Numero
        String sql = "SELECT ID, Usuario, Numero FROM Mensajes";

        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {

            // Crear un modelo de tabla
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Usuario");
            model.addColumn("Número");

            // Agregar los datos al modelo
            while (resultSet.next()) {
                int id = resultSet.getInt("ID");
                String usuario = resultSet.getString("Usuario");
                String numero = resultSet.getString("Numero");
                model.addRow(new Object[]{id, usuario, numero});
            }

            // Establecer el modelo en la tabla
            tbContactos.setModel(model);

        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al acceder a la base de datos: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Siempre cierra la conexión en un bloque finally
        conexionSQL.cerrarConexion();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       mostrarHorarioSeleccionado();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// Configurar Twilio
Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

// Obtener el modelo de la tabla
DefaultTableModel model = (DefaultTableModel) tbContactos.getModel();

// Encontrar el índice de la columna que contiene los números de teléfono
int columnaNumero = model.findColumn("Número");

// Verificar si se encontró la columna
if (columnaNumero != -1) {
    // Iterar sobre las filas de la tabla
    for (int i = 0; i < model.getRowCount(); i++) {
        // Convertir el valor a String
        Object valor = model.getValueAt(i, columnaNumero);
        String telefonoContacto = String.valueOf(valor);

        // Obtener la fecha de envío seleccionada
        java.util.Date fechaEnvioDate = jDateChooser1.getDate();
        java.sql.Date fechaEnvioSQL = new java.sql.Date(fechaEnvioDate.getTime());

        // Enviar mensaje utilizando Twilio
        try {
            Message message = Message.creator(
                    new com.twilio.type.PhoneNumber(telefonoContacto.trim()),
                    new com.twilio.type.PhoneNumber(numero),
                    txtMensaje.getText())
                .create();

            // Guardar el mensaje en la base de datos
            guardarMensajeEnBaseDeDatos(telefonoContacto, txtMensaje.getText(), fechaEnvioSQL);

            JOptionPane.showMessageDialog(null, "Mensaje enviado a " + telefonoContacto + ": " + message.getSid());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al enviar mensaje a " + telefonoContacto + ": " + e.getMessage());
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "La columna 'Número' no fue encontrada en la tabla.");
}

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductorActionPerformed
        ListaUbicaciones ListaUbicaciones=new ListaUbicaciones();
        ListaUbicaciones.setVisible(true);
        
    }//GEN-LAST:event_btnConductorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String mensaje = txtMensaje.getText();

    // Contar caracteres
    int totalCaracteres = mensaje.length();

    // Contar mensajes (asumiendo que cada línea es un mensaje)
    int totalMensajes = mensaje.split("\n").length;

    // Mostrar el resultado en algún lugar, por ejemplo, en un JLabel
    jLabel12.setText("Resultado: Total de caracteres = " + totalCaracteres +
                         ", Total de mensajes = " + totalMensajes);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    
    }//GEN-LAST:event_jButton6ActionPerformed
private void mostrarHorarioSeleccionado() {
    // Obtener la fecha seleccionada del JDateChooser
    Date fechaSeleccionada = jDateChooser1.getDate();

    // Verificar si se seleccionó una fecha
    if (fechaSeleccionada != null) {
        // Crear un objeto Calendar y establecer la fecha seleccionada
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaSeleccionada);

        // Obtener el día, mes y año de la fecha seleccionada
        int dia = calendar.get(Calendar.DAY_OF_MONTH);
        int mes = calendar.get(Calendar.MONTH) + 1; // Sumar 1 ya que los meses se cuentan desde 0
        int año = calendar.get(Calendar.YEAR);

        // Mostrar el horario en los componentes de texto
        jTextField2.setText(Integer.toString(dia));
        jTextField1.setText(Integer.toString(mes));
        jTextField3.setText(Integer.toString(año));
    } else {
        // Si no se seleccionó una fecha, puedes manejarlo según tus necesidades
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
// Método para guardar el mensaje en la base de datos
private void guardarMensajeEnBaseDeDatos(String telefonoContacto, String mensaje, java.sql.Date fechaEnvio) {
    // Establecer la conexión a la base de datos
    ConexionSQL conexionSQL = new ConexionSQL();

    try (Connection connection = conexionSQL.getConnection()) {
        // Consulta SQL para insertar el mensaje
        String sql = "INSERT INTO reporte (Usuario, Numero, Mensaje, fechaEnvio) VALUES (?, ?, ?, ?)";

        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            // Establecer los valores en la consulta
            statement.setString(1, "UsuarioEjemplo"); // Cambia esto según tu lógica de usuario
            statement.setString(2, telefonoContacto);
            statement.setString(3, mensaje);
            statement.setDate(4, fechaEnvio);

            // Ejecutar la consulta de inserción
            statement.executeUpdate();
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar el mensaje en la base de datos: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        // Siempre cierra la conexión en un bloque finally
        conexionSQL.cerrarConexion();
    }
}
    // Variables declarati
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton btnConductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tbContactos;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
