/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sofware_EnvioMensajesAguaCarabayllo.view;


import SoftwareMensagge.view.Dao.CisternaDAO;
import SoftwareMensagge.view.Dao.CisternaDAOImpl;
import SoftwareMensagge.view.Dao.ConductorDAO;
import SoftwareMensagge.view.Dao.ConductorDAOImpl;
import Sofware_EnvioMensajesAguaCarabayll.Controler.Cisterna;
import Sofware_EnvioMensajesAguaCarabayll.Controler.ConductorR;
import Sofware_EnvioMensajesAguaCarabayllo.model.ConexionSQL;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elvis
 */
public class Lista_Conductor_Cisterna extends javax.swing.JFrame {
 private ConexionSQL conexionSQL;
 private DefaultTableModel modeloTabla;
    /**
     * Creates new form Lista_Conductor_Cisterna
     */
    public Lista_Conductor_Cisterna() {
        initComponents();
         conexionSQL = new ConexionSQL();
        modeloTabla = new DefaultTableModel(); // Agrega esta línea
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("nLicencia");
        tbTrabajador.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNumeroLicencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtPlaca = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        txtGrifos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSubirRegistro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTrabajador = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabecera.setBackground(new java.awt.Color(201, 50, 0));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conductor y SIsterna");
        Cabecera.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel11.setText("Lista");
        Cabecera.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel18.setText("Municipalida distrital de Carabayllo");
        Cabecera.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 410, 30));

        jPanel1.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jLabel12.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel12.setText("nombres");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, 30));

        jLabel8.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel8.setText("apellidos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 170, 30));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 120, 30));

        jLabel13.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel13.setText("DNI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel14.setText("EDAD");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 120, 30));

        jLabel15.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel15.setText("N licencia");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        txtNumeroLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroLicenciaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/284-F5-1300 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Capacidad", "nGrifos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 500, 130));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 160, 30));

        jLabel16.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel16.setText("Placa");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel9.setText("Capacidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        jPanel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 170, 30));

        txtGrifos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrifosActionPerformed(evt);
            }
        });
        jPanel1.add(txtGrifos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 120, 30));

        jLabel17.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel17.setText("N grifos");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel10.setText("Lista Conductores");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, 30));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel19.setText("Cisterna:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 120, 30));

        btnRegistrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro-en-linea.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 130, 40));

        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/expediente.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 130, 40));

        btnSubirRegistro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnSubirRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargando.png"))); // NOI18N
        btnSubirRegistro.setText("Subir Empleado");
        btnSubirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubirRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 170, 40));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargando.png"))); // NOI18N
        jButton2.setText("Subir Cisterna");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 170, 40));

        tbTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "DNI", "Edad", "nLicencia"
            }
        ));
        jScrollPane2.setViewportView(tbTrabajador);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 780, 130));

        jButton3.setBackground(new java.awt.Color(245, 71, 9));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver-lista.png"))); // NOI18N
        jButton3.setText("Ver ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, 40));

        jButton4.setBackground(new java.awt.Color(245, 71, 9));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver-lista.png"))); // NOI18N
        jButton4.setText("Ver ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 110, 40));

        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jButton5.setText("Agregar Cisterna");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtNumeroLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroLicenciaActionPerformed

    private void txtGrifosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrifosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrifosActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       int edad = Integer.parseInt(txtEdad.getText());
      String numero_licencia = txtNumeroLicencia.getText();
      String Nombre = txtNombre.getText();
     String apellido = txtApellido.getText();
     String dni = txtDNI.getText();
        ConductorR ConductorR=new ConductorR(edad, numero_licencia, Nombre, apellido, dni);
        DefaultTableModel modeloTabla = (DefaultTableModel) tbTrabajador.getModel();
Object[] fila = {ConductorR.getNombre(), ConductorR.getApellido(),
                 ConductorR.getDni(), ConductorR.getEdad(), ConductorR.getNumero_licencia()};
modeloTabla.addRow(fila);
    
limpiarCamposFormulario();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int[] filasSeleccionadas = tbTrabajador.getSelectedRows();

    if (filasSeleccionadas.length > 0) { // Verificar si hay filas seleccionadas
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar las filas seleccionadas?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Eliminar las filas seleccionadas en orden inverso para evitar problemas de índice
            for (int i = filasSeleccionadas.length - 1; i >= 0; i--) {
                modeloTabla.removeRow(filasSeleccionadas[i]);
            }

            JOptionPane.showMessageDialog(this, "Filas eliminadas correctamente.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione al menos una fila para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
    }               
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSubirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirRegistroActionPerformed
 int filaSeleccionada = tbTrabajador.getSelectedRow();
    if (filaSeleccionada != -1) {
        try {
            // Obtener el valor de la celda de la columna 'Edad' en la fila seleccionada
            Object valorCelda = tbTrabajador.getValueAt(filaSeleccionada, 0);

            // Verificar si el valor de la celda no es nulo y no está vacío
         if (valorCelda != null && !valorCelda.toString().isEmpty()) {
    // Convertir la cadena a un entero
             int edad = Integer.parseInt(tbTrabajador.getValueAt(filaSeleccionada, 3).toString());

                // Obtener los demás valores
                String numero_licencia = tbTrabajador.getValueAt(filaSeleccionada, 4).toString();
                String Nombre = tbTrabajador.getValueAt(filaSeleccionada, 0).toString();
                String apellido = tbTrabajador.getValueAt(filaSeleccionada, 1).toString();
                String dni = tbTrabajador.getValueAt(filaSeleccionada, 2).toString();

                // Crear un objeto ConductorR con la información
                ConductorR ConductorR = new ConductorR(edad, numero_licencia, Nombre, apellido, dni);

                // Instancia del DAO
                ConductorDAOImpl ConductorDAOImpl = new ConductorDAOImpl(conexionSQL.getConnection());

                // Llamada al método DAO
                ConductorDAOImpl.insertarConductor(ConductorR);

                // Remover la fila seleccionada del modelo de la tabla
                DefaultTableModel modelo = (DefaultTableModel) tbTrabajador.getModel();
                modelo.removeRow(filaSeleccionada);

                JOptionPane.showMessageDialog(this, "Datos insertados correctamente en la base de datos.");
            } else {
                // Manejar el caso en que el valor de la celda es nulo o vacío
                JOptionPane.showMessageDialog(this, "El valor de la celda de 'Edad' es nulo o vacío.");
            }
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se puede convertir a entero
            System.err.println("Error al convertir la edad a entero: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al convertir la edad a un entero.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un registro para subir a la base de datos.");
    }
    }//GEN-LAST:event_btnSubirRegistroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada != -1) {
        try {
            String placa = jTable1.getValueAt(filaSeleccionada, 0).toString();
            double capacidad = Double.parseDouble(jTable1.getValueAt(filaSeleccionada, 1).toString());
            int grifos = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 2).toString());

            // Crear un objeto Cisterna con la información
            Cisterna cisterna = new Cisterna(placa, capacidad, grifos);

            // Instancia del DAO (Asumo que el DAO de Cisterna se llama CisternaDAOImpl)
            CisternaDAOImpl cisternaDAOImpl = new CisternaDAOImpl(conexionSQL.getConnection());

            // Llamada al método DAO
            cisternaDAOImpl.insertarCisterna(cisterna);

            // Remover la fila seleccionada del modelo de la tabla
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.removeRow(filaSeleccionada);

            JOptionPane.showMessageDialog(this, "Datos insertados correctamente en la base de datos.");
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se puede convertir a double o entero
            System.err.println("Error al convertir a número: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al convertir a número.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un registro para subir a la base de datos.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Crear una instancia de ConductorDAO, asumiendo que tienes una conexión válida
    ConductorDAO conductorDAO = new ConductorDAOImpl(conexionSQL.getConnection());

    // Llamada al método obtenerConductores
    List<Sofware_EnvioMensajesAguaCarabayll.Controler.ConductorR> conductores = conductorDAO.obtenerConductores();

    // Limpiar la tabla antes de cargar nuevos datos
    DefaultTableModel modeloTabla = (DefaultTableModel) tbTrabajador.getModel();
    modeloTabla.setRowCount(0);

    // Agregar los conductores a la tabla
    for (Sofware_EnvioMensajesAguaCarabayll.Controler.ConductorR conductor : conductores) {
        Object[] fila = {conductor.getEdad(), conductor.getNumero_licencia(), conductor.getNombre(),
            conductor.getApellido(), conductor.getDni()};
        modeloTabla.addRow(fila);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Crear una instancia de CisternaDAO, asumiendo que tienes una conexión válida
CisternaDAOImpl cisternaDAO = new CisternaDAOImpl(conexionSQL.getConnection());

// Llamada al método obtenerCisternas
List<Sofware_EnvioMensajesAguaCarabayll.Controler.Cisterna> cisternas = cisternaDAO.obtenerCisternas();

// Limpiar la tabla antes de cargar nuevos datos
DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
modeloTabla.setRowCount(0);

// Agregar las cisternas a la tabla
for (Sofware_EnvioMensajesAguaCarabayll.Controler.Cisterna cisterna : cisternas) {
    Object[] fila = {cisterna.getPlaca(), cisterna.getCapacidad(), cisterna.getGrifos()};
    modeloTabla.addRow(fila);
}
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

       String placa=txtPlaca.getText();
       double capacidad=Double.parseDouble(txtCapacidad.getText());
       int grifos=Integer.parseInt(txtGrifos.getText());
        Cisterna Cisterna=new Cisterna(placa, capacidad, grifos);
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
Object[] fila = {Cisterna.getPlaca(), Cisterna.getCapacidad(),
                 Cisterna.getGrifos()};
modeloTabla.addRow(fila);
    
limpiarCamposFormulario();      
    }//GEN-LAST:event_jButton5ActionPerformed
private void limpiarCamposFormulario() {
    txtEdad.setText("");
    txtNumeroLicencia.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtDNI.setText("");
}
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSubirRegistro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbTrabajador;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGrifos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
